Add controllers
DmitrySheyko/java-shareit pull request #1
Opened 2022-10-21 08:07 UTC by DmitrySheyko

Проект: java-shareit.
Разработан код в соответствиии с ТЗ спринта 14.

2022-10-21 15:46 UTC, Frilock requested changes
Добрый день, пара небольших комментариев к работе, если что пишите.

2022-10-21 15:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDtoForUpdate.getId() == null) {
Такую конструкцию можно на Optional переписать, Optional.ofNullable(...), посмотрите синтаксис

2022-10-21 15:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.isBlank()) {
А не лучше ли проверять через StringUtils.isBlank, чтобы NPE избегать?

2022-10-21 15:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    Map<Long, Item> mapOfItems;
Почему не приватное поле?

2022-10-21 18:39 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    Map<Long, Item> mapOfItems;
Исправление внесено

2022-10-21 19:27 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDtoForUpdate.getId() == null) {
Внес правки. Выглядит сложнее, но метод стал намного компактнее.

2022-10-21 19:55 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.isBlank()) {
Так лучще. Исправил. Буду знать про такую возможность. Спасибо.

2022-10-22 07:49 UTC, Frilock approved these changes
Принял, но 1 комментарий оставил, посмотрите.

2022-10-22 07:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        itemDtoForUpdate.setId(Optional.ofNullable(itemDtoForUpdate.getId()).orElse(itemFromStorage.getId()));
Не совсем то, что я имел ввиду - Optional.ofNullable(itemDto.getId()).ifPresent(itemDto::setId), по моему так, потыкайтесь =)

2022-11-01 11:34 UTC, merged