Add bookings
DmitrySheyko/java-shareit pull request #2
Opened 2022-11-07 16:40 UTC by DmitrySheyko

Финальный проект спринта № 15.
Ветка Add bookings

2022-11-08 16:48 UTC, Frilock requested changes
Добрый вечер. Оставил ряд комментариев к работе

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +@SpringBootApplication(//exclude={DataSourceAutoConfiguration.class},
Лучше убрать закомментированный код

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingResponseDto add(@RequestHeader("X-Sharer-User-Id") Long bookerId,
Публичные модификаторы забыли, в других контроллерах у вас стоят они

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +
Лишние пустые строчки

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +        } else {
Блок else не нужен, у Вас же в if return есть

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    private final ItemServiceImpl itemServiceImpl;
Правильнее инжектить интерфейс, а не реализацию, как минимум, будет гораздо проще писать тесты

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Instant start;
Воу, а почему такой тип выбран?) Я в своей практике не видел, чтобы его использовали в продакшне

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repositiory/BookingRepository.java
> +            "b.start < ?2  and " +
По моему мы можем на between заменить, разве нет ?

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repositiory/BookingRepository.java
> +    @Query(" select b " +
Вообще честно говоря, хотелось бы, чтобы чистых SQLек было бы по минимуму, вы же все таки со spring-data работаете, лучше по максимуму в название метода умещать запрос

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static final String ALL_REQUEST = "ALL";
Давайте просто enum создадим

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingForUpdate.getStatus().equals(BookingStatus.APPROVED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            booking = optionalBooking.get();
Кажется что логичнее сюда эту строку воткнуть         return userId.equals(booking.getBookerId());

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        itemRequestDto.setId(itemId);
Лучше эту логику в сервис перенести, в контролере обычно только валидация

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemServiceImpl itemServiceImpl;
Нужно инжектить интерфейс, проверьте в других местах

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        List<Booking> listOfBookings = bookingRepository.findLastBookingsByItemId(itemId, Instant.now());
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Table
А почему наименование таблицы не указали?

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private String text;
Для строковых полей лучше еще размерность указывать как в скриптах.

2022-11-08 16:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Transient
А зачем поле это игнорировать? Для чего его добавлять тогда

2022-11-08 16:48 UTC, Frilock commented on src/main/resources/application.properties
> +# ????????? ??? ???? Postgres
А для чего оставляете?

2022-11-09 07:57 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +@SpringBootApplication(//exclude={DataSourceAutoConfiguration.class},
Убрал. Изначально программа выдавала ошибку о двух драйверах для БД и я искал способы ее решить. Забыл убрать.

2022-11-09 08:00 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingResponseDto add(@RequestHeader("X-Sharer-User-Id") Long bookerId,
Исправил.

2022-11-09 08:01 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +
Исправил

2022-11-09 08:06 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +        } else {
Внес исправления

2022-11-09 08:08 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    private final ItemServiceImpl itemServiceImpl;
Абсолютно согласен, поправил.

2022-11-09 08:25 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Instant start;
Выбрал Instant по следующим причинам:
1) Он не зависит от временных зон т.к. привязанк общепринятома абсолютному значению. Т.е. из таблицы с таким значением можно передать данные пользователю в любой регион и его комп сможет получить точное время сделав поправку на свою временную зону. При этом, не надо обмениваться данными о временной зоне (какая зона на вашем сервере).
2) Из Instant легко получить все доугие типы времени. 
3)  Класс удобен в работе.
4) Имеет короткое название , что делает код немного более чистым и кратким:)

2022-11-09 09:36 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static final String ALL_REQUEST = "ALL";
Сделал

2022-11-09 09:38 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingForUpdate.getStatus().equals(BookingStatus.APPROVED)) {
Поменя. Спасибо, учту на будущее.

2022-11-09 09:42 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            booking = optionalBooking.get();
Переделал. Метод стал покороче.

2022-11-09 09:58 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        itemRequestDto.setId(itemId);
Иван, если не возражаете, я оставлю это без изменений, т.к. на логику не влияет, и мне так больше нравится. Мне нарвится что обмен данными проходит одним специально созданным для этого паремтром ItemRequestDto.
Но, в продолжении проекта и последующих проектах я обязательно подумаю как сделать еще лучше.

2022-11-09 09:59 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemServiceImpl itemServiceImpl;
Поменял во всех сущностях

2022-11-09 10:12 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        List<Booking> listOfBookings = bookingRepository.findLastBookingsByItemId(itemId, Instant.now());
Заменил.

2022-11-09 10:14 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Table
Не заметил, спасибо, исправил.

2022-11-09 10:23 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private String text;
Поправил. Спасибо.

2022-11-09 10:26 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Transient
Как я понял из ТЗ, это поле потребуется нам следующих частях проекта.

2022-11-09 10:30 UTC, DmitrySheyko commented on src/main/resources/application.properties
> +# ????????? ??? ???? Postgres
Мы работаем на базе H2, но в ТЗ также предлагалось проработать подключение к базе Postgre. Я подключил проект к Postgre и когда вернулся к H2 закомментировал данные настройки. 
Нам также обещали на днях в вебинаре показать как создавать и запускать разные профили. Думаю в последующем эти настройки вынесу в отдельный профиль

2022-11-09 12:22 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/repositiory/BookingRepository.java
> +    @Query(" select b " +
Внес правки. Просто мне JPQL нравится больше из за наглядности, более широкого функционала и возможности давать методам хорошо читаемые имена.

2022-11-09 12:25 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/repositiory/BookingRepository.java
> +            "b.start < ?2  and " +
По моему через between не получится

2022-11-09 16:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repositiory/BookingRepository.java
> +    @Query(" select b " +
Согласен =)

2022-11-09 16:37 UTC, Frilock approved these changes
Особых возражений нет, на все вопросы ответили, принял

2022-11-11 23:01 UTC, merged