Add item requests
DmitrySheyko/java-shareit pull request #3
Opened 2022-11-17 23:30 UTC by DmitrySheyko

Выполнены требования ТЗ № 15

2022-11-21 19:03 UTC, Frilock requested changes
Добрый день, в целом все ок, несколько небольших комментариев.

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private User booker;
А зачем меняете? Вообще лучше работать в dto-шках, с дтошками.

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private ItemRepository itemRepository;
Зачем final убрали?

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          } else {
блок else не нужен, внутри if есть return

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/itemRequestMapper/ItemRequestMapper.java
> +@AllArgsConstructor
По моему это лишняя аннотация, не вижу использования ее

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    ItemRequestRepository itemRequestRepository;
Модификаторы потеряли

2022-11-21 19:03 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        } else {
Лишний else

2022-11-21 19:03 UTC, Frilock commented on src/test/java/ru/practicum/shareit/ShareItAppTest.java
> +class ShareItAppTest {
А что этот тест проверяет? Старт контекста проверяет [ShareItTests.java]

2022-11-21 19:03 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +    User user = User.builder().id(1L).name("UserName1").email("User1@email.com").build();
Модификаторы к полям

2022-11-21 19:03 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/repositiory/BookingRepositoryTest.java
> +    TestEntityManager em;
Модификатор

2022-11-21 19:03 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/repositiory/BookingRepositoryTest.java
> +//TODO
Меня такой комментарий смущает =) Вы либо его убирайте, либо делайте доработку которую хотели

2022-11-21 19:03 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        BookingRequestDto bookingFromOwner = BookingRequestDto.builder().bookerId(ownerOfItem).start(start).end(end)
Вижу во многих тестах создание одного и того же объекта. Сделайте метод init с аннотацией BeforeEach, в котором будете создавать обьект. Он будет перед каждым тестом выполнятся.
Кроме того, зачем Вам транзакция над всеми тестами?

2022-11-21 19:03 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        Assertions.assertThrows(ObjectNotFoundException.class, () -> bookingService.add(bookingFromOwner));
Помимо того, что вы проверяете, что было выброшено исключение, так же проверяйте сообщение из него, чтобы быть точно уверенным, что произошла та ошибка, которую вы ожидали. (через contains)

2022-11-21 23:08 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private User booker;
Не помню почему поменял, но сейчас вернул обратно. Идея про dto в dto-шках кажется логичной.

2022-11-21 23:25 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
Убрал во всех репозиториях. Изначально поставил ее потому, что так было показано в предлагаемых нам материалах для ознакомления с темой: https://howtodoinjava.com/spring-boot2/testing/datajpatest-annotation/
Хотя там толком не обяснено зачем они используют эту аннотацию в интерфейсе.

2022-11-21 23:30 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private ItemRepository itemRepository;
Вернул на место. Изначально бины необходимые для тестов не удавалось получить я много эксперементировал в том числе с модификаторами доступа:)

2022-11-21 23:32 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          } else {
Понял. Убрал.

2022-11-21 23:36 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/request/itemRequestMapper/ItemRequestMapper.java
> +@AllArgsConstructor
Согласен. Конструктор тут не нужен и аннотация тоже.

2022-11-21 23:37 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    ItemRequestRepository itemRequestRepository;
Поправил.

2022-11-21 23:39 UTC, DmitrySheyko commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        } else {
Исправил. Логику понял. В дальнейшем учту.

2022-11-21 23:43 UTC, DmitrySheyko commented on src/test/java/ru/practicum/shareit/ShareItAppTest.java
> +class ShareItAppTest {
Тест удалил. Я его создал, и долго думал как же  класс ShareItApp проверить. Ниего не придумал. А теперь узнал про ShareItTests.java. Спасибо.

2022-11-21 23:44 UTC, DmitrySheyko commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +    User user = User.builder().id(1L).name("UserName1").email("User1@email.com").build();
Сделал.

2022-11-21 23:48 UTC, DmitrySheyko commented on src/test/java/ru/practicum/shareit/booking/repositiory/BookingRepositoryTest.java
> +    TestEntityManager em;
Внес правки.

2022-11-21 23:51 UTC, DmitrySheyko commented on src/test/java/ru/practicum/shareit/booking/repositiory/BookingRepositoryTest.java
> +//TODO
Убрал. Странно что при загрузке коммента меня система о нем не предупредила.  Обычно сообщалось.

2022-11-22 00:03 UTC, DmitrySheyko commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        BookingRequestDto bookingFromOwner = BookingRequestDto.builder().bookerId(ownerOfItem).start(start).end(end)
@Transaction  ставил чтобы методы add и update не изменяли мою базу данных и не надо было вручную приводить ее в исходное состояние перед следующим тестом. Ставил над классом, тк не видел в этом вреда.

2022-11-22 10:19 UTC, DmitrySheyko commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        Assertions.assertThrows(ObjectNotFoundException.class, () -> bookingService.add(bookingFromOwner));
Доработал

2022-11-22 14:00 UTC, Frilock approved these changes
Принято

2022-11-26 07:42 UTC, merged