Add docker
DmitrySheyko/java-shareit pull request #4
Opened 2022-11-30 08:47 UTC by DmitrySheyko

Реализовано ТЗ спринта 17

2022-11-30 14:20 UTC, Frilock requested changes
Добрый день, посмотрел работу:
1. На ревью попали файлы из папки tagret, зачем вы удалили gitignore файл? Файлы на ревью попадать не должны.
2. Ряд мелких комментариев
3. Вижу что вы удаляете большую часть тестовых классов из проекта. Зачем ? Перенесите их

2022-11-30 14:20 UTC, Frilock commented on .gitignore
> -HELP.md
Зачем удаляете файлик? На ревью приходит 211 файлов, включая папку таргет, что не верно. Нужно поправить

2022-11-30 14:20 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +@Validated
А для чего она тут? Не вижу применения, мб поправите меня

2022-11-30 14:20 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/user/UserClient.java
> +        if (requestDto.getName() != null) {
По идее можно Optiona.ofNullable(...).ifPresent(...)

2022-11-30 14:20 UTC, Frilock commented on gateway/target/classes/application.properties
> +#logging.level.org.apache.http=DEBUG
Надо убрать неиспользуемый код

2022-11-30 14:20 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
Без этой строчки у вас не работает?

2022-11-30 14:20 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/exceptions/Error.java
> +    String error;
Модификатор приватный

2022-11-30 14:20 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +//    @ExceptionHandler(ConstraintViolationException.class)
Нужно убрать закомментированный код

2022-11-30 14:20 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
>  @Validated
Эту не забыли убрать?

2022-11-30 15:14 UTC, DmitrySheyko commented on .gitignore
> -HELP.md
Лишние файлы убрал. Извиняюсь за путаницу с файлами. Вышел из строя мой ноут и пришлось пересобирать проект на чужом. На нервах перед жестким дедлайном натворил дел.

2022-11-30 15:30 UTC, DmitrySheyko commented on gateway/target/classes/application.properties
> +#logging.level.org.apache.http=DEBUG
Поправил

2022-11-30 15:31 UTC, DmitrySheyko commented on server/src/main/java/ru/practicum/shareit/exceptions/Error.java
> +    String error;
Добавил, спасибо

2022-11-30 15:34 UTC, DmitrySheyko commented on server/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +//    @ExceptionHandler(ConstraintViolationException.class)
Код убрал

2022-11-30 15:36 UTC, DmitrySheyko commented on server/src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
>  @Validated
Убрал.

2022-11-30 16:35 UTC, DmitrySheyko commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
Еще раз перепроверил. Без этой строчки приложение запускается на порту 8080, несмотря на указание порта 9090 в applicatiom.properties. Также проверил в структуре проекта то, что aplication.properties указаны как resourses.

2022-11-30 16:35 UTC, DmitrySheyko commented on gateway/src/main/java/ru/practicum/shareit/user/UserClient.java
> +        if (requestDto.getName() != null) {
Переделал. Стало более кратко.

2022-11-30 16:35 UTC, DmitrySheyko commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +@Validated
Убрал.
Аннотация здесь не требуется. Ранее пробовал делать валидацию параметров поступающих в метод update(). Но потом отказался от этой идеи.

2022-12-01 19:17 UTC, Frilock commented on .gitignore
> -HELP.md
Файлы не пропали, вы видимо добавили гит игнор, но файлы старые не удалили. В общем надо бы до конца разобраться

2022-12-01 19:17 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
Так конфигурировать все равно не правильно, давайте попробуем сходить к наставнику или коллегам с вопросом.

2022-12-01 19:19 UTC, Frilock requested changes
Добрый вечер, файлы из targer все равно на ревью, надо разобраться. По поводу конфигурирования порта модуля, давайте этот вопрос зададим наставникам и коллегам, мб у кого то была похожая проблема.

2022-12-02 13:15 UTC, DmitrySheyko commented
> Добрый вечер, файлы из targer все равно на ревью, надо разобраться. По поводу конфигурирования порта модуля, давайте этот вопрос зададим наставникам и коллегам, мб у кого то была похожая проблема.

Добрый день. В этот раз файлы из папки target удалил все вручную, а не только добавил в GitIgnore.
Исправил ошибку с запуском программы на неправильном порту. Думаю у меня это была "плавающая" проблема, связанная с несколькими факторами, среди которых:
- неправильное применение параметра spring.config.activate.on-profile ci,test;
- проверка результатов изменений кода без пересборки jar  или докер-образа;
- также, возможно, при прочтении логов запуска программы, мог взглянуть не на то параметр который мне был нужен.
Я экспериментировал с разными параметрами, совершаю то одну, то другую ошибку.

2022-12-03 09:06 UTC, Frilock approved these changes
Принято

2023-02-07 09:39 UTC, merged